spring.application.name=hotelcalifornia

spring.datasource.url=jdbc:mysql://trolley.proxy.rlwy.net:22071/railway
spring.datasource.username=root
spring.datasource.password=IVeeJtKLTVqXAXHpsdJjNKXtSevQYATD
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true  

server.port=8081
server.servlet.context-path=/api